<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admin-PC" ignored="0" name="Open Account" tests="5" failures="1" timestamp="2019-10-30T02:53:26 EET" time="12.151" errors="0">
  <testcase name="openAccountTest" time="1.859" classname="bankManager.testcases.OpenAccountTest"/>
  <testcase name="openAccountTest" time="0.839" classname="bankManager.testcases.OpenAccountTest"/>
  <testcase name="openAccountTest" time="0.036" classname="bankManager.testcases.OpenAccountTest">
    <skipped/>
  </testcase> <!-- openAccountTest -->
  <testcase name="openAccountTest" time="0.869" classname="bankManager.testcases.OpenAccountTest"/>
  <testcase name="openAccountTest" time="0.852" classname="bankManager.testcases.OpenAccountTest">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: 
Expected: a string containing &amp;quot;Aaaaaaaaaa&amp;quot;
     but: was &amp;quot;Account created successfully with account Number :1019&amp;quot;">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: 
Expected: a string containing "Aaaaaaaaaa"
     but: was "Account created successfully with account Number :1019"
at bankManager.testcases.OpenAccountTest.openAccountTest(OpenAccountTest.java:50)
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.AssertionError: 
Expected: a string containing "Aaaaaaaaaa"
     but: was "Account created successfully with account Number :1019"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at bankManager.testcases.OpenAccountTest.openAccountTest(OpenAccountTest.java:43)
... 28 more
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- openAccountTest -->
</testsuite> <!-- Open Account -->
