<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admin-PC" ignored="0" name="Test" tests="5" failures="1" timestamp="2019-10-18T07:14:15 EEST" time="14.587" errors="0">
  <testcase name="openAccountTest" time="1.426" classname="bankManager.testcases.OpenAccountTest"/>
  <testcase name="openAccountTest" time="0.831" classname="bankManager.testcases.OpenAccountTest"/>
  <testcase name="openAccountTest" time="0.779" classname="bankManager.testcases.OpenAccountTest"/>
  <testcase name="openAccountTest" time="0.79" classname="bankManager.testcases.OpenAccountTest"/>
  <testcase name="openAccountTest" time="0.841" classname="bankManager.testcases.OpenAccountTest">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: 
Expected: a string containing &amp;quot;Aaaaaaaaaa&amp;quot;
     but: was &amp;quot;Account created successfully with account Number :1020&amp;quot;">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: 
Expected: a string containing "Aaaaaaaaaa"
     but: was "Account created successfully with account Number :1020"
at bankManager.testcases.OpenAccountTest.openAccountTest(OpenAccountTest.java:51)
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.AssertionError: 
Expected: a string containing "Aaaaaaaaaa"
     but: was "Account created successfully with account Number :1020"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at bankManager.testcases.OpenAccountTest.openAccountTest(OpenAccountTest.java:44)
... 28 more
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- openAccountTest -->
</testsuite> <!-- Test -->
